# Generated by Django 2.1.5 on 2019-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('song_id', models.IntegerField()),
                ('corver_pic', models.CharField(max_length=500)),
                ('song_src', models.CharField(max_length=500)),
                ('song_name', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=100)),
                ('song_user_name', models.CharField(max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
